spring:
  application:
    name: shardingsphere-demo
  #    datasource:
  #        driver-class-name: com.mysql.cj.jdbc.Driver
  #        url: jdbc:mysql://192.168.3.17:33067/test?serverTimezone=Asia/Shanghai
  #        username: root
  #        password: ******

  # 配置 DataSource Driver
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # 指定 YAML 配置文件 sharding-jdbc.yaml
    url: jdbc:shardingsphere:classpath:sharding-jdbc.yaml

